# global search settings
use_icons:    true
ignore_case:  true
search_regex: false

# window settings
window:
  title: "Rmenu - Application Launcher"
  size:
    width:  800
    height: 400
  position:
    x: 300
    y: 500
  focus:       true
  decorate:    false
  transparent: false
  always_top:  true

# configured plugin settings
plugins:
  run:  
    exec:  ["~/.config/rmenu/rmenu-run"]
    cache: 300
  drun: 
    exec:  ["~/.config/rmenu/rmenu-desktop"]
    cache: onlogin
  audio:
    exec:  ["~/.config/rmenu/rmenu-audio"]
    cache: false
    placeholder: "Select an Audio Sink"
  network:
    exec:  ["~/.config/rmenu/rmenu-network"]
    cache: false
    placeholder: "Connect to the Specified Wi-Fi"
  window:
    exec:  ["~/.config/rmenu/rmenu-window"]
    cache: false
    placeholder: "Jump to the Specified Window"

# custom keybindings
keybinds:
  exec:       ["Enter"]
  exit:       ["Escape"]
  move_next:  ["Arrow-Down", "Tab"]
  move_prev:  ["Arrow-Up", "Shift+Tab"]
  open_menu:  ["Arrow-Right"]
  close_menu: ["Arrow-Left"]
