[package]
name    = "rmenu"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.2"
cached = "0.44.0"
clap = { version = "4.3.15", features = ["derive"] }
dioxus = "0.3.2"
dioxus-desktop = "0.3.0"
env_logger = "0.10.0"
heck = "0.4.1"
keyboard-types = "0.6.2"
log = "0.4.19"
png = "0.17.9"
quick-xml = "0.30.0"
regex = { version = "1.9.1" }
resvg = "0.35.0"
rmenu-plugin = { version = "0.0.0", path = "../rmenu-plugin" }
serde = { version = "1.0.171", features = ["derive"] }
serde_json = "1.0.103"
serde_yaml = "0.9.24"
shell-words = "1.1.0"
shellexpand = "3.1.0"
thiserror = "1.0.43"
