[package]
name = "rmenu"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
askama = "0.12.1"
base64 = "0.21.5"
clap = { version = "4.4.11", features = ["derive"] }
env_logger = "0.10.1"
heck = "0.4.1"
keyboard-types = "0.7.0"
lastlog = { version = "0.2.3", features = ["libc"] }
log = "0.4.20"
once_cell = "1.19.0"
png = "0.17.10"
rayon = "1.8.0"
regex = "1.10.2"
resvg = "0.36.0"
rmenu-plugin = { version = "0.0.1", path = "../rmenu-plugin" }
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
serde_yaml = "0.9.27"
shell-words = "1.1.0"
shellexpand = "3.1.0"
strfmt = "0.2.4"
thiserror = "1.0.50"
web-view = "0.7.3"
which = "5.0.0"
