[package]
name = "rmenu-plugin"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "rmenu_plugin"
path = "src/lib.rs"

[[bin]]
name = "rmenu-build"
path = "src/bin/main.rs"
required-features = ["cli"]

[features]
default = []
cli = ["clap", "serde_json"]

[dependencies]
clap = { version = "4.3.22", features = ["derive"], optional = true }
serde = { version = "1.0.171", features = ["derive"] }
serde_json = { version = "1.0.105", optional = true }
